#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
debug: false

spring:
  ## Thymeleaf configuration:
  thymeleaf:
    cache: false
    mode: HTML5
  resources:
    cache-period: 0
  ## H2 Servlet setting
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2

  # Embedded Database
  datasource:
    url: jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Turn off Security for Actuator:
management:
  security:
    enabled: false


##---------------------------------------------------------------------------##
