#------------------------------------------------------------------------------#
# Application YAML #
# inside ./src/main/resources/application.yml
#------------------------------------------------------------------------------#
debug: false

spring:
#  resource:
#    chain:
#      enabled: true

  ## Thymeleaf configuration (see ThymeleafConfig.java)
#  thymeleaf:
#    cache: false
#    mode: HTML5
#  resources:
#    cache-period: 0

  ## H2 Servlet setting
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2

  # Embedded Database
  datasource:
    url: jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    # These properties are only needed to dump the JPA generated ddl to a file:
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: build/create.sql

# Turn off Security for Actuator:
management:
  security:
    enabled: false


## Chapter 8 TLS over HTTP/1.1:
## https://localhost:8443
server:
  port: 8443
  ssl:
    key-store: "classpath:keys/jbcp_clientauth.p12"
    key-store-password: changeit
    keyStoreType: PKCS12
    keyAlias: jbcpclient
    protocol: TLS

## CAS Properties
# Calendar is our Service:
cas.calendar.service.login: https://localhost:8443/login

# CAS Is our Server:
cas.server: https://localhost:9443/cas

##---------------------------------------------------------------------------##
